# -*- coding: utf-8 -*-
"""DETR training

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JQusyJctT0dRvgW2LS9SUeYAU3nSkALX
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!git clone https://github.com/thedeepreader/detr_tutorial.git

!pip install -r /content/drive/MyDrive/tut/detr/requirements.txt

!pip install torch==1.7.0 torchvision==0.8.1

# Commented out IPython magic to ensure Python compatibility.
# %run /content/drive/MyDrive/tut/detr/main.py --dataset_file face --data_path ../dataset/ --output_dir /content/drive/MyDrive/detr_output --resume https://dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth

# Commented out IPython magic to ensure Python compatibility.
# %run /content/drive/MyDrive/tut/detr/test.py --data_path /content/drive/MyDrive/tut/celebrity_dataset/train/zendaya_coleman  --resume /content/drive/MyDrive/detr_output/checkpoint.pth --output_dir /content/drive/MyDrive/detr_output/cropped_zc/test